services:
  opensearch-node:
    image: ghcr.io/perfsonar/opensearch-node:5.3.0
    container_name: opensearch-node
    restart: always
    platform: linux/amd64
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "perfSONAR123!"
      DISABLE_INSTALL_DEMO_CONFIG: true
      cluster.name: opensearch-cluster
      node.name: opensearch-node
      discovery.type: single-node
      bootstrap.memory_lock: true              # disables swapping
      network.host: "0.0.0.0"                  # required for non-demo config
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - opensearch-config:/usr/share/opensearch/config
      - perfsonar-config:/etc/perfsonar
      - logstash-env:/env
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer
    healthcheck:
      test: [ "CMD-SHELL", "curl --insecure --silent --fail https://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    

  perfsonar-logstash:
    image: ghcr.io/perfsonar/logstash:5.3.0
    container_name: perfsonar-logstash
    restart: always
    platform: linux/amd64
    environment:
      MONITORING_ENABLED: false
      LOG_LEVEL: info
      RATE_CACHE_MAX_ENTRIES: 10000000
      RATE_CACHE_EXPIRES: 600
      opensearch_output_host: "https://opensearch-node:9200"
      opensearch_output_user: pscheduler_logstash
    entrypoint: >
      /bin/sh -c "
        export $(cat /env/logstash.env);
        exec /usr/local/bin/docker-entrypoint
      "
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - logstash-env:/env
    ports:
      - 11283:11283
    expose:
      - "11283"
    depends_on:
      opensearch-node:
        condition: service_healthy

  opensearch-dashboards:
    profiles: ["dashboards"]
    image: ghcr.io/perfsonar/opensearch-dashboards:5.3.0
    container_name: opensearch-dashboards
    restart: always
    platform: linux/amd64
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node:9200"]' # must be a string with no spaces when specified as an environment variable
      SERVER_HOST: "0.0.0.0"
    volumes:
      - perfsonar-config:/etc/perfsonar
    ports:
      - 5601:5601
    expose:
      - "5601"
    depends_on:
      opensearch-node:
        condition: service_healthy

  perfsonar-grafana:
    profiles: ["grafana"]
    image: ghcr.io/perfsonar/grafana:5.3.0
    container_name: perfsonar-grafana
    restart: always
    environment:
      - OPENSEARCH_URL=https://opensearch-node:9200
      - OPENSEARCH_VERSION=2.19.4
      - GF_INSTALL_PLUGINS=grafana-opensearch-datasource,esnet-matrix-panel
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PATHS_PROVISIONING=/usr/lib/perfsonar/grafana/provisioning
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
       - 3000:3000
    expose:
      - "3000"
    depends_on:
      opensearch-node:
        condition: service_healthy

volumes:
  opensearch-data:
  opensearch-config:
  perfsonar-config:
  logstash-env: