---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
  name: {{ .Release.Name }}-archive-libs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
  name: {{ .Release.Name }}-dashboards-libs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
  name: {{ .Release.Name }}-logstash-libs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
data:
  pre_script: |
    #!/bin/bash
    apt-get update
    apt-get install -y git make maven
    git clone --branch 5.2.0 https://github.com/perfsonar/logstash.git logstash-git
    make -C logstash-git/perfsonar-logstash/perfsonar-logstash ROOTPATH=/usr/lib/perfsonar/logstash CONFIGPATH=/usr/lib/perfsonar/logstash SYSTEMDPATH=/etc/systemd/system install
    chown -R 1000:1000 /usr/lib/perfsonar/logstash
    git clone --branch 5.2.0 https://github.com/perfsonar/archive.git archive-git    
    make -C archive-git/perfsonar-archive/perfsonar-archive PERFSONAR-ROOTPATH=/usr/lib/perfsonar/archive LOGSTASH-ROOTPATH=/usr/lib/perfsonar/logstash HTTPD-CONFIGPATH=/etc/http SYSTEMD-CONFIPATH=/etc/systemd/system BINPATH=/usr/bin install
    chown -R 1000:1000 /usr/lib/perfsonar/archive
    make -C archive-git/perfsonar-dashboards/perfsonar-dashboards DASHBOARDS-ROOTPATH=/usr/lib/perfsonar/dashboards HTTPD-CONFIGPATH=/etc/http install
    chown -R 1000:1000 /usr/lib/perfsonar/dashboards
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
  name: perfosnar-preinstall-script

---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    job-name: hello
  name: hello
spec:
  backoffLimit: 6
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    spec:
      containers:
        - args:
            - /usr/local/bin/downloader.sh
          command:
            - /bin/bash
          image: debian:stable
          imagePullPolicy: IfNotPresent
          name: perfsonar-preinstall
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /usr/local/bin/downloader.sh
              name: perfosnar-preinstall-script
              subPath: pre_script   
            - mountPath: /usr/lib/perfsonar/logstash
              name: {{ .Release.Name }}-logstash-libs-pvc
            - mountPath: /usr/lib/perfsonar/archive
              name: {{ .Release.Name }}-archive-libs-pvc
            - mountPath: /usr/lib/perfsonar/dashboards
              name: {{ .Release.Name }}-dashboards-libs-pvc
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      volumes:
        - name: perfosnar-preinstall-script
          configMap:
            name: perfosnar-preinstall-script
        - name: {{ .Release.Name }}-archive-libs-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-archive-libs-pvc
        - name: {{ .Release.Name }}-dashboards-libs-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-dashboards-libs-pvc
        - name: {{ .Release.Name }}-logstash-libs-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logstash-libs-pvc
