apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: {{ .Values.logstash.image.repository }}:{{ .Values.logstash.image.tag }}
          imagePullPolicy: {{ .Values.logstash.image.pullPolicy }}
          env:
            - name: MONITORING_ENABLED
              value: "false"
            - name: LOG_LEVEL
              value: "info"
            - name: RATE_CACHE_MAX_ENTRIES
              value: "10000000"
            - name: RATE_CACHE_EXPIRES
              value: "600"
            - name: opensearch_output_host
              value: "{{ include "perfsonar-archive.fullname" . }}-opensearch-node"
            - name: opensearch_output_user
              value: {{ .Values.logstash.opensearch_output_user }}
          ports:
            - containerPort: 11283