apiVersion: v1
kind: Service
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-opensearch-node
spec:
  selector:
    app: opensearch-node
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9600
      targetPort: 9600