apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-logstash-credentials
type: Opaque
stringData:
  username: {{ .Values.logstash.opensearch_output_user | quote }}
  password: {{ default (randAlphaNum 20) .Values.logstash.opensearch_output_password | quote }}
