{{- $secretName := printf "%s-logstash-credentials" (include "perfsonar-archive.fullname" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
stringData:
  username: {{ .Values.logstash.opensearch_output_user | quote }}
  {{- if $existingSecret }}
  password: {{ index $existingSecret.data "password" | b64dec | quote }}
  {{- else }}
  password: {{ default (randAlphaNum 20) .Values.logstash.opensearch_output_password | quote }}
  {{- end }}