apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-opensearch-node
spec:
  serviceName: {{ include "perfsonar-archive.fullname" . }}-opensearch-node
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-node
  template:
    metadata:
      labels:
        app: opensearch-node
    spec:
      containers:
        - name: opensearch-node
          image: {{ .Values.opensearchNode.image.repository }}:{{ .Values.opensearchNode.image.tag }}
          imagePullPolicy: {{ .Values.opensearchNode.image.pullPolicy }}
          env:
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: {{ .Values.opensearchNode.initialAdminPassword | quote }}
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: cluster.name
              value: "opensearch-cluster"
            - name: node.name
              value: "opensearch-node"
            - name: discovery.type
              value: "single-node"
            - name: bootstrap.memory_lock
              value: "true"
            - name: network.host
              value: "0.0.0.0"
            - name: LOGSTASH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "perfsonar-archive.fullname" . }}-logstash-credentials
                  key: password
          ports:
            - containerPort: 9200
            - containerPort: 9600
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
            - name: opensearch-shared
              mountPath: /etc/perfsonar/opensearch
  volumeClaimTemplates:
    - metadata:
        name: opensearch-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.opensearchNode.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.opensearchNode.persistence.size }}
