apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-opensearch-shared
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "1Mi" }}
