{{- $secretName := printf "%s-logstash-credentials" (include "perfsonar-archive.fullname" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
stringData:
  username: {{ .Values.logstash.opensearch_output_user | quote }}
  password: {{
    if $existingSecret
      (index $existingSecret.data "password" | b64dec)
    else
      (default (randAlphaNum 20) .Values.logstash.opensearch_output_password)
    end
  | quote }}