{{- if .Values.apache.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-apache
spec:
  type: {{ .Values.apache.service.type }}
  selector:
    app: apache-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: {{ .Values.apache.service.port }}
      targetPort: {{ .Values.apache.service.targetPort }}
      protocol: TCP
{{- end }}