apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-opensearch-shared
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.opensearchNode.persistence.storageClass }}
  resources:
    requests:
      storage: 10Mi
