apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-opensearch-shared
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.opensearchNode.persistence.storageClassName }}
  storageClassName: {{ .Values.opensearchNode.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: 10Mi
