{{- if and .Values.opensearch.enabled (not .Values.opensearch.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-opensearch-admin
  labels:
    {{- include "perfsonar-archive.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: {{ required "opensearch.initialAdminPassword is required" .Values.opensearch.initialAdminPassword | quote }}
{{- end }}
