# Global settings
global:
  perfsonarVersion: "5.2.0"

perfsonarDownloader:
  image:
    repository: ghcr.io/perfsonar/perfsonar-archive-docker/perfsonar-downloader
    tag: "5.2.0"
    pullPolicy: Always

opensearchNode:
  image:
    repository: ghcr.io/perfsonar/perfsonar-archive-docker/opensearch-node
    tag: 5.2.0
    pullPolicy: Always
  opensearchVersion: "2.18.0"
  initialAdminPassword: "perfSONAR123!"
  persistence:
    enabled: true
    storageClass: "standard" # Or your preferred storage class
    size: 10Gi

logstash:
  image:
    repository: ghcr.io/perfsonar/perfsonar-archive-docker/logstash
    tag: 5.2.0
    pullPolicy: Always
  logstashVersion: "8.17.3"

opensearchDashboards:
  image:
    repository: ghcr.io/perfsonar/perfsonar-archive-docker/opensearch-dashboards
    tag: 5.2.0
    pullPolicy: Always
  opensearchVersion: "2.18.0"