# Global settings
global:
  perfsonarVersion: "5.2.0"

perfsonar-downloader:
  image:
    repository: perfsonar/perfsonar-downloader # Replace with your image repository
    tag: "5.2.0"
    pullPolicy: Always

opensearch-node:
  image:
    repository: perfsonar/opensearch-node # Replace with your image repository
    tag: 5.2.0
    pullPolicy: Always
  opensearchVersion: "2.18.0"
  initialAdminPassword: "perfSONAR123!"
  persistence:
    enabled: true
    storageClass: "standard" # Or your preferred storage class
    size: 10Gi

logstash:
  image:
    repository: perfsonar/logstash # Replace with your image repository
    tag: 5.2.0
    pullPolicy: Always
  logstashVersion: "8.17.3"

opensearch-dashboards:
  image:
    repository: perfsonar/opensearch-dashboards # Replace with your image repository
    tag: 5.2.0
    pullPolicy: Always
  opensearchVersion: "2.18.0"