# Global settings
global:
  perfsonarVersion: "5.3.0"

opensearchNode:
  image:
    repository: ghcr.io/perfsonar/opensearch-node
    tag: 5.3.0
    pullPolicy: Always
  opensearchVersion: "2.19.4"
  initialAdminPassword: "perfSONAR123!"
  persistence:
    enabled: true
    storageClass: "standard" # Or your preferred storage class
    size: 10Gi

logstash:
  image:
    repository: ghcr.io/perfsonar/logstash
    tag: 5.3.0
    pullPolicy: Always
  logstashVersion: "8.17.3"
  opensearch_output_user: "pscheduler_logstash"

opensearchDashboards:
  image:
    repository: ghcr.io/perfsonar/opensearch-dashboards
    tag: 5.3.0
    pullPolicy: Always
  opensearchVersion: "2.19.4"